name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd proje/GorevTakipProgrami
          docker build -t gorev-takip-programi .
          docker stop gorev-takip-container || true
          docker rm gorev-takip-container || true
          docker run -d --name gorev-takip-container -p 8080:80 gorev-takip-programi
